from __future__ import annotations

from mechcal.capabilities import CapabilityRegistry
from mechcal.schemas import (
    CaseRun,
    DiagnosisUnit,
    EvidenceUnit,
    MechanismProgram,
    ScopeBoundary,
)


def build_empty_mechanism_agenda(
    case_run: CaseRun,
    *,
    round_id: str,
    capability_registry: CapabilityRegistry,
) -> MechanismProgram:
    del capability_registry
    return MechanismProgram(
        program_id=f"{case_run.case_id}:{round_id}:mechanism_agenda_disabled",
        case_id=case_run.case_id,
        round_id=round_id,
        candidate_mechanisms=[],
        evidence_questions=[],
        computational_routes=[],
        scope_boundaries=[
            ScopeBoundary(
                boundary_id="legacy_programmatic_agenda_disabled",
                statement=(
                    "Programmatic mechanism agenda generation is disabled. Use "
                    "MechanismAgendaAgent with an LLM client for scientific agenda "
                    "proposal."
                ),
            ),
            ScopeBoundary(
                boundary_id="agenda_not_final_diagnosis",
                statement=(
                    "This compatibility record contains no scientific mechanism "
                    "agenda and is not a final mechanism diagnosis."
                ),
            ),
        ],
    )


def build_mechanism_program(
    case_run: CaseRun,
    *,
    round_id: str,
    capability_registry: CapabilityRegistry,
) -> MechanismProgram:
    """Compatibility alias: returns a mechanism agenda, not a diagnosis program."""

    return build_empty_mechanism_agenda(
        case_run,
        round_id=round_id,
        capability_registry=capability_registry,
    )


def build_diagnosis_units(case_run: CaseRun) -> list[DiagnosisUnit]:
    """Project the Planner's final portfolio into DA units.

    This deliberately avoids deriving diagnosis units from mechanism agenda,
    Arbiter review cards, or hard-coded case-family rules. If an LLM-driven
    ConclusionLedger is present, use its Planner-grounded diagnosis conclusions.
    """

    if case_run.diagnosis_units:
        return list(case_run.diagnosis_units)
    if case_run.final_answer and case_run.final_answer.diagnosis_units:
        return list(case_run.final_answer.diagnosis_units)
    if case_run.conclusion_ledger and case_run.conclusion_ledger.diagnosis_conclusions:
        return [
            DiagnosisUnit(
                diagnosis_id=item.conclusion_id,
                mechanism=item.mechanism,
                context="ConclusionLedgerAgent runtime record",
                status=item.status,
                evidence_refs=item.source_evidence_refs,
                missing_or_unresolved=item.missing_or_unresolved,
                reasoning_summary=item.reasoning_summary,
                scope_limits=item.scope_limits,
            )
            for item in case_run.conclusion_ledger.diagnosis_conclusions
        ]

    current = (case_run.portfolio.current or "unknown").strip() or "unknown"
    evidence_refs = [
        item.evidence_id
        for item in case_run.evidence_ledger.items
        if item.status in {"present", "partial"}
    ]
    scope_limits = [
        "Diagnosis is generated by Planner final synthesis from public typed evidence.",
        "Mechanism agenda entries are questions and boundaries, not final conclusions.",
    ]
    if current == "unknown" or not evidence_refs:
        return [
            DiagnosisUnit(
                diagnosis_id="D001",
                mechanism="Planner mechanism assessment unresolved",
                context="Planner final synthesis",
                status="underdetermined",
                missing_or_unresolved=[
                    "Planner did not have enough typed evidence to support a final "
                    "mechanism family."
                ],
                reasoning_summary=(
                    "The evidence ledger is insufficient for a supported Planner "
                    "mechanism assessment."
                ),
                scope_limits=scope_limits,
            )
        ]

    computed_support = any(
        item.basis == "computed" and item.support == "supports"
        for item in case_run.evidence_ledger.items
    )
    status = "computed_supported" if computed_support else "proxy_supported"
    return [
        DiagnosisUnit(
            diagnosis_id="D001",
            mechanism=current,
            context="Planner final synthesis",
            status=status,
            evidence_refs=evidence_refs[:8],
            missing_or_unresolved=[
                "Wet-lab, material, or high-level excited-state evidence may still "
                "be required for source-level claims."
            ],
            reasoning_summary=(
                "Planner selected this working mechanism family from the final "
                "hypothesis portfolio and the public typed evidence ledger."
            ),
            scope_limits=scope_limits,
        )
    ]


def build_scientific_evidence_units(
    case_run: CaseRun,
    *,
    diagnosis_units: list[DiagnosisUnit] | None = None,
) -> list[EvidenceUnit]:
    """No-op by design.

    Planner diagnosis should cite existing worker evidence. The mechanism agenda
    must not synthesize new evidence units because that would blur evidence
    collection with final scientific judgment.
    """

    return []
