from __future__ import annotations

MECHANISM_POOL = (
    "RIM_RIR_RIV",
    "PACKING_HOST_MATRIX_CONFINEMENT",
    "HOST_GUEST_INTERACTION",
    "ICT_TICT_CT",
    "ESIPT_PT",
    "PET_ET",
    "AGGREGATE_EXCITON_EXCIMER",
    "RADIATIVE_RATE_STATE_BALANCE",
    "TRIPLET_METAL_ENERGY_TRANSFER",
    "RACI_CI_ACCESS",
    "SOKR_ANTI_KASHA",
)
